### PR TITLE
4071 - Filtering of cluster elements in AI agent

### LINKED ISSUE #4071: [bug] Filtering of cluster elements does not work in the Cluster Element editor
Steps to reproduce:

1. Add an AI Agent node
2. Click on it to open the Cluster Element editor
3. Click on the plus button for tools
4. Start typing a component name in the filter field

Current behaviour:
None of the components is visible

Expected behaviour:
Only components matching the filtering word are shown

### PR DESCRIPTION
**Pull request by petrapaz**
fixes #4071 

### 1. AI Agent / Cluster Element popover

- Cluster Elements tab: client-side filtering now matches component name/title and action/trigger name/title, aligning with backend search behavior.
- In cluster element mode, Actions and Triggers lists now show only components that support the selected cluster element type (e.g. tools), using a shared hasClusterElementType helper.
- Task dispatchers (Flows) now use a trimmed filter so their behavior is consistent with other tabs and leading/trailing spaces do not break the search.
image
image

## 

> **this is a follow up on last PR #3988 considering filtering triggers and actions:**
### 2. Components & Flow Controls (right sidebar) - update its filter logic

Problem
- The Components & Flow Controls sidebar (WorkflowNodesSidebar) did not use backend search. Filtering was applied only on the client side using component name/title from the store, without debounce and without trimming the input.

Solution
- Reused the same backend search as in the popover: useGetComponentDefinitionsWithActionsQuery(trimmedFilter) when the user enters text.
- Added a 300 ms debounce and trimmed filter, matching the popover behavior.
- Actions, Triggers, and Flows lists are built from search results when the filter is non-empty and data is loaded; otherwise, they fall back to store data.
- Flows are filtered by trimmed name/title.
image

### CODE REVIEW

File: client/src/pages/platform/workflow-editor/components/WorkflowNodesPopoverMenuComponentList.tsx [hunk 1]
```diff
@@ -85,60 +97,67 @@ const WorkflowNodesPopoverMenuComponentList = memo(
...
-                                        element.type?.name === convertNameToSnakeCase(clusterElementType as string)
-                                );
+                                if (trimmedFilter) {
+                                    return true;
+                                }
 
-                                return (
-                                    (hasClusterElementsCount || hasClusterElements) && (nameIncludes || titleIncludes)
-                                );
+                                return true;
```
Comment (kresimir-coko) [inline client/src/pages/platform/workflow-editor/components/WorkflowNodesPopoverMenuComponentList.tsx]: može se pojednostavniti:
```js
componentsWithActions.filter((component) => hasClusterElementType(component, clusterElementType)).filter(({name}) => (!ff_3839 && name !== 'aiAgent') || ff_3839)
```

jer `trimmedFilter` je truthy ako postoji `componentsWithActions`

File: client/src/pages/platform/workflow-editor/components/WorkflowNodesSidebar.tsx [hunk 2]
```diff
@@ -13,48 +18,56 @@ const WorkflowNodesSidebar = ({
     };
 }) => {
     const [filter, setFilter] = useState('');
+    const [debouncedFilter] = useDebounce(filter, 300);
```
Comment (kresimir-coko) [inline client/src/pages/platform/workflow-editor/components/WorkflowNodesSidebar.tsx:22]: fali prazan red - ne znan kako točno opisati razlog, ali nije korištenje istog hooka pa zahtjeva odvajanje

File: client/src/pages/platform/workflow-editor/components/WorkflowNodesPopoverMenuComponentList.tsx
Comment (kresimir-coko) [inline client/src/pages/platform/workflow-editor/components/WorkflowNodesPopoverMenuComponentList.tsx]: Možemo poboljšati performanse sa ovim blokom:
```js
const {ff_797, ff_1652, ff_3827, ff_3839, ff_4000} = useFeatureFlagsStore(
    useShallow((state) => ({
        ff_1652: state('ff-1652'),
        ff_3827: state('ff-3827'),
        ff_3839: state('ff-3839'),
        ff_4000: state('ff-4000'),
        ff_797: state('ff-797'),
    }))
);
```

Razlog je to šta se samo 1 put subscribe-amo na store, a ne 5 puta.

Znan da nije dio tvog koda - ali ako želimo biti dobri inženjeri onda želimo ostaviti kod boljim nego šta smo ga pronašli 😉  a ovo je quick-win

Comment (petrapaz) [reply client/src/pages/platform/workflow-editor/components/WorkflowNodesPopoverMenuComponentList.tsx]: @kresimir-coko izbacivalo mi je dosta ESLint errora: 

- Expected 0 arguments, but got 1.
- 'state' is of type '`unknown`'
- Property '`ff_4000`' does not exist on type '`(featureFlag: string) => boolean`'
...

implementirala sam 1 subscription na store (samo jedan poziv `useFeatureFlagsStore()`)
komponenta se re-renderira kad se promijeni `featureFlags` objekt

nije idealno koliko san istrazivala (re-renderira se i kad se promijeni flag koji ova komponenta ne koristi) ali mogu u iducem PR-u istrazit bolje rjesenje

Comment (kresimir-coko) [reply client/src/pages/platform/workflow-editor/components/WorkflowNodesPopoverMenuComponentList.tsx]: Ništa, @petrapaz vrati kako je bilo šta se tiče ovog. Problem je u tome šta `useFeatureFlagsStore` nije zustand store iako se zove kao zustand store (Store suffix) - i onda koncept subscribanja i typescript ne radi kako bi triba
