### PR TITLE
2816 - Include the authorizationType in the ConnectionParameters comp…

### LINKED ISSUE #2816: [bug]: Component connection displays incorrect connection summary
### Describe the bug

When I select connection Authorization type: Basic Auth for components HTTP Client and Liferay API Client
and I set username and password
and I save connection
then connection summary visible in Connection Edit View or in Components Connection Tab displays Digest Auth together with Basic Auth.

Image

### Steps To Reproduce

1. go to connections view
2. create new connection for HTTP Client - name it HTTP TEST Connection
3. select Authorization: Basic Auth
4. populate required fields with test data
5. Save
6. Click Edit on HTTP TEST Connection
7. **Basic and Digest Auth is visible in summary**

### Expected behavior

Expected
Only summary for Basic Auth is visible as it is authorization method selected during setup
Actually:
Digest Auth is visible which confuses user. It does not influence component functionality but it is not correct information.

### Version

2.3.1

### OS

macos

### Browser

chrome (latest)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by monikakuster**
…onent to filter existing authorizations based on type

Fixes #2816

### CODE REVIEW

File: client/src/shared/components/connection/ConnectionParameters.tsx [hunk 1]
```diff
@@ -35,6 +38,11 @@ const ConnectionParameters = ({
     const hasAuthorizationParameters =
         existingAuthorizations && authorizationParameters && !!Object.keys(authorizationParameters).length;
 
+    console.log('connectionDefinition: ', connectionDefinition);
+    console.log('connectionParameters: ', connectionParameters);
+    console.log('authorizationParameters: ', authorizationParameters);
+    console.log('authorizationType: ', authorizationType);
+
```
Comment (kresimir-coko) [inline client/src/shared/components/connection/ConnectionParameters.tsx]: ❌

**Review by kresimir-coko — CHANGES_REQUESTED** [review]
